# 1. 정수 num1, num2가 매개변수 주어집니다. num1과 num2를 곱한 값을 return 하도록 solution 함수를 완성해주세요.

<h4>제한사항</h4>

<ul>
<li>0 ≤ <code>num1</code> ≤ 100</li>
<li>0 ≤ <code>num2</code> ≤ 100</li>
</ul>

<hr>

<h4>입출력 예</h4>
<table class="table">
        <thead><tr>
<th>num1</th>
<th>num2</th>
<th>result</th>
</tr>
</thead>
        <tbody><tr>
<td>3</td>
<td>4</td>
<td>12</td>
</tr>
<tr>
<td>27</td>
<td>19</td>
<td>513</td>
</tr>
</tbody>
      </table>
<hr>

<h4>입출력 예 설명</h4>

<p>입출력 예 #1</p>

<ul>
<li><code>num1</code>이 3, <code>num2</code>가 4이므로 3 * 4 = 12를 return합니다.</li>
</ul>

<p>입출력 예 #2</p>

<ul>
<li><code>num1</code>이 27, <code>num2</code>가 19이므로 27 * 19 = 513을 return합니다.</li>
</ul>

In [ ]:
def solution1(num1, num2):
    answer = num1 _ num2
    return answer

####

if all([solution1(3, 4) == 12,
        solution1(27, 19) == 513]):
    print("정답입니다!")

# 2. 정수 num1과 num2가 매개변수로 주어집니다. 두 수가 같으면 1 다르면 -1을 retrun하도록 solution 함수를 완성해주세요.

<h5>제한사항</h5>

<ul>
<li>0 ≤ <code>num1</code> ≤ 10,000</li>
<li>0 ≤ <code>num2</code> ≤ 10,000</li>
</ul>

<hr>

<h5>입출력 예</h5>
<table class="table">
        <thead><tr>
<th>num1</th>
<th>num2</th>
<th>result</th>
</tr>
</thead>
        <tbody><tr>
<td>2</td>
<td>3</td>
<td>-1</td>
</tr>
<tr>
<td>11</td>
<td>11</td>
<td>1</td>
</tr>
<tr>
<td>7</td>
<td>99</td>
<td>-1</td>
</tr>
</tbody>
      </table>
<hr>

<h5>입출력 예 설명</h5>

<p>입출력 예 설명 #1</p>

<ul>
<li><code>num1</code>이 2이고 <code>num2</code>가 3이므로 다릅니다. 따라서 -1을 return합니다.</li>
</ul>

<p>입출력 예 설명 #2</p>

<ul>
<li><code>num1</code>이 11이고 <code>num2</code>가 11이므로 같습니다. 따라서 1을 return합니다.</li>
</ul>

<p>입출력 예 설명 #3</p>

<ul>
<li><code>num1</code>이 7이고 <code>num2</code>가 99이므로 다릅니다. 따라서 -1을 return합니다.</li>
</ul>

In [ ]:
def solution2(num1, num2):
    __ num1 __ num2:
        return _
    ____:
        return _

####

if all([solution2(2, 3) == -1,
        solution2(11, 11) == 1,
        solution2(7, 99) == -1]):
    print("정답입니다!")

# 3. 한국이는 41살인 선생님이 몇 년도에 태어났는지 궁금해졌습니다. 나이 age가 주어질 때, 2023년을 기준 출생 연도를 return 하는 solution 함수를 완성해주세요.

<h5>제한사항</h5>

<ul>
<li>0 < age ≤ 120</li>
<li>나이는 태어난 연도에 1살이며 1년마다 1씩 증가합니다. </li>
</ul>

<hr>

<h5>입출력 예</h5>
<table class="table">
        <thead><tr>
<th>age</th>
<th>result</th>
</tr>
</thead>
        <tbody><tr>
<td>41</td>
<td>1983</td>
</tr>
<tr>
<td>24</td>
<td>2000</td>
</tr>
</tbody>
      </table>
<hr>

<h5>입출력 예 설명</h5>

<p>입출력 예 #1</p>

<ul>
<li>2023년 기준 41살이므로 1983년생입니다.</li>
</ul>

<p>입출력 예 #2</p>

<ul>
<li>2023년 기준 24살이므로 2000년생입니다.</li>
</ul>

In [ ]:
def solution3(age):
    answer = ____ - age
    return answer

####

if all([solution3(41) == 1983,
        solution3(24) == 2000]):
    print("정답입니다!")

# 4. 정수 배열 numbers가 매개변수로 주어집니다. numbers의 원소 중 두 개를 곱해 만들 수 있는 최댓값을 return하도록 solution 함수를 완성해주세요.

<h5>제한사항</h5>

<ul>
<li>0 ≤ <code>numbers</code>의 원소 ≤ 10,000</li>
<li>2 ≤ <code>numbers</code>의 길이 ≤ 100</li>
</ul>

<hr>

<h5>입출력 예</h5>
<table class="table">
        <thead><tr>
<th>numbers</th>
<th>result</th>
</tr>
</thead>
        <tbody><tr>
<td>[1, 2, 3, 4, 5]</td>
<td>20</td>
</tr>
<tr>
<td>[0, 31, 24, 10, 1, 9]</td>
<td>744</td>
</tr>
</tbody>
      </table>
<hr>

<h5>입출력 예 설명</h5>

<p>입출력 예 #1</p>

<ul>
<li>두 수의 곱중 최댓값은 4 * 5 = 20 입니다.</li>
</ul>

<p>입출력 예 #1</p>

<ul>
<li>두 수의 곱중 최댓값은 31 * 24 = 744 입니다.</li>
</ul>

In [ ]:
def solution4(numbers):
    maxvalue = 0
    for i in _____(___(numbers)-1):
        for j in range(i+1, len(numbers)):
            if numbers[i]*numbers[j] _ maxvalue:
                maxvalue = numbers[i]*numbers[j]
    answer = maxvalue
    return answer

####

if all([solution4([1,2,3,4,5]) == 20,
        solution4([0, 31, 24, 10, 1, 9]) == 744]):
    print("정답입니다!")

# 5. 정수가 담긴 리스트 num_list가 주어질 때, num_list의 원소 중 짝수와 홀수의 개수를 담은 배열을 return 하도록 solution 함수를 완성해보세요.

<h5>제한사항</h5>

<ul>
<li>1 ≤ <code>num_list</code>의 길이 ≤ 100</li>
<li>0 ≤ <code>num_list</code>의 원소 ≤ 1,000</li>
</ul>

<hr>

<h5>입출력 예</h5>
<table class="table">
        <thead><tr>
<th>num_list</th>
<th>result</th>
</tr>
</thead>
        <tbody><tr>
<td>[1, 2, 3, 4, 5]</td>
<td>[2, 3]</td>
</tr>
<tr>
<td>[1, 3, 5, 7]</td>
<td>[0, 4]</td>
</tr>
</tbody>
      </table>
<hr>

<h5>입출력 예 설명</h5>

<p>입출력 예 #1</p>

<ul>
<li>[1, 2, 3, 4, 5]에는 짝수가 2, 4로 두 개, 홀수가 1, 3, 5로 세 개 있습니다.</li>
</ul>

<p>입출력 예 #2</p>

<ul>
<li>[1, 3, 5, 7]에는 짝수가 없고 홀수가 네 개 있습니다.</li>
</ul>

In [1]:
def solution5(num_list):
    짝수갯수 = 0
    홀수갯수 = 0
    for i in num_list:
        if i % 2:
            ____ += 1
        else:
            ____ += 1
    answer = [짝수갯수, 홀수갯수]
    return answer

####

if all([solution5([1,2,3,4,5]) == [2, 3],
        solution5([1,3,5,7]) == [0, 4]):
    print("정답입니다!")

# 6. 정수가 담긴 배열 array와 정수 n이 매개변수로 주어질 때, array에 n이 몇 개 있는 지를 return 하도록 solution 함수를 완성해보세요.

<h5>제한사항</h5>

<ul>
<li>1 ≤ <code>array</code>의 길이 ≤ 100</li>
<li>0 ≤ <code>array</code>의 원소 ≤ 1,000</li>
<li>0 ≤ <code>n</code> ≤ 1,000</li>
</ul>

<hr>

<h5>입출력 예</h5>
<table class="table">
        <thead><tr>
<th>array</th>
<th>n</th>
<th>result</th>
</tr>
</thead>
        <tbody><tr>
<td>[1, 1, 2, 3, 4, 5]</td>
<td>1</td>
<td>2</td>
</tr>
<tr>
<td>[0, 2, 3, 4]</td>
<td>1</td>
<td>0</td>
</tr>
</tbody>
      </table>
<hr>

<h5>입출력 예 설명</h5>

<p>입출력 예 #1</p>

<ul>
<li>[1, 1, 2, 3, 4, 5] 에는 1이 2개 있습니다.</li>
</ul>

<p>입출력 예 #2</p>

<ul>
<li>[0, 2, 3, 4] 에는 1이 0개 있습니다.</li>
</ul>

In [ ]:
def solution6(array, n):
    answer = array._____(n)
    return answer

####

if all([solution6([1,1,2,3,4,5], 1) == 2,
        solution6([0,2,3,4], 1) == 0]):
    print("정답입니다!")

# 7. 문자열 my_string과 문자 letter이 매개변수로 주어집니다. my_string에서 letter를 제거한 문자열을 return하도록 solution 함수를 완성해주세요.

<h5>제한사항</h5>

<ul>
<li>1 ≤ <code>my_string</code>의 길이 ≤ 100</li>
<li><code>letter</code>은 길이가 1인 영문자입니다.</li>
<li><code>my_string</code>과 <code>letter</code>은 알파벳 대소문자로 이루어져 있습니다.</li>
<li>대문자와 소문자를 구분합니다.</li>
</ul>

<hr>

<h5>입출력 예</h5>
<table class="table">
        <thead><tr>
<th>my_string</th>
<th>letter</th>
<th>result</th>
</tr>
</thead>
        <tbody><tr>
<td>"abcdef"</td>
<td>"f"</td>
<td>"abcde"</td>
</tr>
<tr>
<td>"BCBdbe"</td>
<td>"B"</td>
<td>"Cdbe"</td>
</tr>
</tbody>
      </table>
<hr>

<h5>입출력 예 설명</h5>

<p>입출력 예 #1</p>

<ul>
<li>"abcdef" 에서 "f"를 제거한 "abcde"를 return합니다.</li>
</ul>

<p>입출력 예 #2</p>

<ul>
<li>"BCBdbe" 에서 "B"를 모두 제거한 "Cdbe"를 return합니다.</li>
</ul>

In [ ]:
def solution7(my_string, letter):
    return my_string._______(letter, "")

####

if all([solution7("abcdef", "f") == "abcde",
        solution7("BCBdbe", "B") == "Cdbe"]):
    print("정답입니다!")

# 8. 정수 n이 주어질 때, n이하의 짝수를 모두 더한 값을 return 하도록 solution 함수를 작성해주세요.

<h5>제한사항</h5>

<p>0 < <code>n</code> ≤ 1000</p>

<hr>

<h5>입출력 예</h5>
<table class="table">
        <thead><tr>
<th>n</th>
<th>result</th>
</tr>
</thead>
        <tbody><tr>
<td>10</td>
<td>30</td>
</tr>
<tr>
<td>4</td>
<td>6</td>
</tr>
</tbody>
      </table>
<hr>

<h5>입출력 예 설명</h5>

<p>입출력 예 #1</p>

<ul>
<li><code>n</code>이 10이므로 2 + 4 + 6 + 8 + 10 = 30을 return 합니다.</li>
</ul>

<p>입출력 예 #2</p>

<ul>
<li><code>n</code>이 4이므로 2 + 4 = 6을 return 합니다.</li>
</ul>

In [ ]:
def solution8(n):
    answer = 0
    for i in range(_________):
        answer += i
    return answer

####

if all([solution8(10) == 30,
        solution8(4) == 6]):
    print("정답입니다!")

# 9. 현재시각을 "2023년 7월 18일 화요일 12시 48분 00초"라는 문자열로 리턴하는 함수를 작성해주세요. (datetime 모듈 이용)

In [ ]:
import datetime as dt


def solution9():
    현재연월일시 = dt.datetime.___()
    요일인덱스 = "월화수목금토일"[현재연월일시._______()]
    answer = 현재연월일시.________(f"__년 %#_월 __d일 {요일인덱스}요일 %#H시 %#M분 %#S초")
    return answer

solution9()

# 출력예시 : "2023년 7월 18일 화요일 12시 48분 00초"

# 10. 아래 src 문자열 중 영문 단어만 추출하여 리스트로 리턴하는 함수를 작성해주세요. (re 모듈 이용)

In [ ]:
import re

src = """
XYZ Two Tuck Belted Slaks
- semi wide fit으로 제작된 세련된 design의 belted slax
- slax 전문 factory에서 제작, high quality
- 탄탄하고 부드러운 원단으로 오랫동안 daily하게 착용할 수 있는 제품
- 여유있는 silhouette과 span 함유 원단, 편안한 착용감
- 선택에 폭이 넓은 size
- 깔끔한 two tuck detail로 여름 codi에 다양하게 활용하기 좋은 daily한 item"""


def solution(src):
    return re.findall(r"[______]_", src)

solution(src)

# 옳은 출력 : ['XYZ', 'Two', 'Tuck', 'Belted', 'Slaks', 'semi', 'wide', 'fit', 'design', 'belted', 'slax',
#              'slax', 'factory', 'high', 'quality', 'daily', 'silhouette', 'span', 'size', 'two', 'tuck',
#              'detail', 'codi', 'daily', 'item']

# 보너스문제(10점)
# 위의 출력을 ["XYZ Two Tuck Belted Slaks", "semi wide fit", "design", "belted slax", "slax", "factory", "high quality",
#              "daily", "silhouette", "span", "two tuck detail", "codi", "daily", "item"] 처럼
# 스페이스가 들어있는 영단어 묶음을 한 개의 문자열로 추출하여 리스트를 리턴하는 함수 solution11(src)를 작성해주세요.